# Generated by Django 5.2.17 on 2026-09-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0005_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profils",
                to="inventory.company",
                verbose_name="entreprise",
            ),
        ),
    ]
