# Generated by Django 5.2.17 on 2026-09-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_hero",
            field=models.BooleanField(
                default=False,
                help_text="Cochez cette case pour mettre cette catégorie en avant dans l'espace de vente.",
                verbose_name="Afficher en héro",
            ),
        ),
    ]
