# Generated by Django 5.2.17 on 2026-09-04 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_category_is_hero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="personne de contact"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="adresse")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="référence"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("commande", "Commandée"),
                            ("partielle", "Partiellement livrée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_commande",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de commande"
                    ),
                ),
                (
                    "date_livraison_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="livraison prévue"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_commande_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
                (
                    "entrepot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_commande",
                        to="inventory.warehouse",
                        verbose_name="entrepôt de destination",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="inventory.supplier",
                        verbose_name="fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_commandee",
                    models.PositiveIntegerField(
                        default=1, verbose_name="quantité commandée"
                    ),
                ),
                (
                    "quantite_recue",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantité reçue"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="prix unitaire",
                    ),
                ),
                (
                    "bon_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_achat",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de bon de commande",
                "verbose_name_plural": "Lignes de bon de commande",
            },
        ),
        migrations.CreateModel(
            name="ReorderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_min",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Niveau de stock qui déclenche une alerte.",
                        verbose_name="stock minimum",
                    ),
                ),
                (
                    "quantite_cible",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Quantité à viser après réapprovisionnement.",
                        verbose_name="quantité cible",
                    ),
                ),
                (
                    "delai_livraison_jours",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Délai estimé entre la commande et la réception.",
                        verbose_name="délai de livraison (jours)",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "entrepot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regles_reapprovisionnement",
                        to="inventory.warehouse",
                        verbose_name="entrepôt",
                    ),
                ),
                (
                    "produit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_rule",
                        to="inventory.product",
                        verbose_name="produit",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regles",
                        to="inventory.supplier",
                        verbose_name="fournisseur principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de réapprovisionnement",
                "verbose_name_plural": "Règles de réapprovisionnement",
            },
        ),
    ]
