# Generated by Django 5.2.17 on 2026-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_supplier_purchaseorder_purchaseorderitem_reorderrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="nom de l'entreprise"
                    ),
                ),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=200, verbose_name="slogan"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/", verbose_name="logo"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="site web")),
                (
                    "rccm",
                    models.CharField(
                        blank=True,
                        help_text="Registre du Commerce et du Crédit Mobilier",
                        max_length=50,
                        verbose_name="RCCM",
                    ),
                ),
                (
                    "id_national",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID National / NIF"
                    ),
                ),
                (
                    "numero_impot",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro Impôt"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="FC", max_length=10, verbose_name="devise"
                    ),
                ),
                (
                    "separateur_milliers",
                    models.CharField(
                        default=" ", max_length=1, verbose_name="séparateur de milliers"
                    ),
                ),
                (
                    "prefixe_symbole",
                    models.BooleanField(
                        default=True, verbose_name="symbole avant le montant"
                    ),
                ),
                (
                    "mentions_footer",
                    models.TextField(
                        blank=True,
                        help_text="Texte affiché en bas de chaque document PDF",
                        verbose_name="mentions en pied de page",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "ordering": ["nom"],
            },
        ),
    ]
